#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH.unshift(File.expand_path("lib", __dir__))
require "adversarial_review"

exit AdversarialReview::CLI.run(ARGV, program_path: File.realpath(__FILE__))
